[package]
name = "rotten-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }
uuid = { version = "1", features = [ "v4" ] }

webp = "0.2"
image = "0.24.0"
